### PR TITLE
Fix shadowing of type names by variant case record names

### LINKED ISSUE #4896: Variant enum case field types can be shadowed by the case record names
The C# variant enum mapping nests one record class per case inside the union record. Since #4877, case parameter types that live in the same namespace as the enum are emitted unqualified. Inside the nested scope, the case record names shadow namespace-level type names, so a field type whose name matches any case name binds to the wrong type.

For example:

```slice
module Example

struct Interface { name: string }

enum Symbol {
    Interface(v: Interface)
}
```

generates:

```csharp
internal abstract partial record class Symbol
{
    partial record class Interface(Interface V) : Symbol
```

where the parameter type `Interface` binds to `Symbol.Interface` itself, producing `error CS8910: The primary constructor conflicts with the synthesized copy constructor.` A collision with a *different* case name silently binds to that sibling case record instead.

Observed by running the `Regenerate` target on `src/ZeroC.Slice.Symbols`: `slice/Compiler/CodeGenerator.slice` wraps each symbol type in a `Symbol` union whose case names match the wrapped types, and the regenerated `CodeGenerator.cs` no longer compiles. The checked-in `Compiler` files must stay on the pre-#4877 output until this is fixed.

Fix direction: fully qualify case parameter types inside the union body — unqualified same-namespace names are inherently unsafe in that nested scope.

### PR DESCRIPTION
**Pull request by bernardnormier**
Fixes #4896.

The variant enum mapping nests one case record per case inside the union record, so within the union body the case record names shadow same-namespace type names. The case parameter list and the case `Encode` method now emit fully qualified type names (empty current namespace).

The parameter list regressed in #4877; the `Encode` method exposure predates it — a tagged (or otherwise lambda-encoded) field whose type name matches a case name produced code that binds the type name to the sibling case record (`error CS8121`). It went unnoticed because no variant enum had such a field.

The new `ShadowedSymbol` enum in `VariantEnumTests.slice` covers both: a self-colliding case (`MyStruct(v: MyStruct)`), and colliding optional and tagged fields. Compiling the generated code is the regression test; #4898 tracks runtime coverage for struct-typed variant fields, a pre-existing test gap that is independent of shadowing.

The second commit regenerates the checked-in `src/ZeroC.Slice.Symbols/Compiler` files with the fixed generator: only the version stamps change, confirming the fix restores the exact output these files were generated with.

## What's Changed entry

Area: Slice codec

- Fixed the generated code for variant enums whose case names match the type names used by their fields.

### CODE REVIEW

**Review by externl — APPROVED** [review]
Looks good.

File: src/ZeroC.Slice.Generator/VariantEnumGenerator.cs [hunk 1]
```diff
@@ -132,9 +132,12 @@ private static CodeBlock GenerateVariantRecord(
     {
         string variantName = variant.Name;
 
+        // Inside the union record, the case record names shadow the type names of the enclosing namespace. We set
+        // currentNamespace to "" to generate fully qualified type names for the parameter list and the encode method.
```
Comment (InsertCreativityHere) [inline src/ZeroC.Slice.Generator/VariantEnumGenerator.cs]: Big fan of adding a comment so we don't accidentally remove this again!
A slight tweak though, since this isn't something that always happens. In reality it should be rare.
```suggestion
        // Inside the union record, the case record names can shadow type names from the enclosing namespace. We set
        // currentNamespace to "" to generate fully qualified type names for the parameter list and the encode method.
```

**Review by InsertCreativityHere — APPROVED** [review]
Looks good to me!

File: src/ZeroC.Slice.Generator/VariantEnumGenerator.cs (hunk 1 above)
Comment (bernardnormier) [reply src/ZeroC.Slice.Generator/VariantEnumGenerator.cs]: Applied, thanks.
